server:
  port: 8082
spring:
  application:
    name: kie-server
eureka:
  client:
    health-checker:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 2
  instance:
    lease-renewal-interval-in-seconds: 2
