server:
  port: 8821

spring:
  application:
    name: tphw-service-kie-server

eureka:
  instance:
    preferIpAddress: true
    appname: tphw-service-kie-server
    virtualHostName: ${eureka.instance.appname}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.102.12:8761/eureka/
deploy:
  releaseIds:
    - com.cntaiping.fsc.bpm:quotation:1.0.2
